name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for reporting an issue. We will start working on your request as soon as possible. Wait for further updates or requests in the comments."
        pr-message: "Thank you for contributing a Pull Request. We will begin reviewing your request as soon as possible. Wait for further updates or requests in the comments."
