"""

name: The-Bocchette-2 Actions
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repository
      uses: actions/checkout@v2

    - name: Setup di Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Installa dipendenze
      run: npm install

    - name: Esegui i test
      run: npm test

"""