name: The-Bocchette-2 Actions
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repository
      uses: actions/checkout@v4  # Aggiornamento a actions/checkout@v4

    - name: Setup di Node.js
      uses: actions/setup-node@v4  # Aggiornamento a actions/setup-node@v4
      with:
        node-version: '20'

    - name: Installa dipendenze
      run: npm install

    - name: Esegui i test
      run: npm test
